services:
  fiap.cloudgames.fase1.api:
    image: ${DOCKER_REGISTRY-}fiapcloudgamesfase1api
    container_name: fiapcloudgamesfase1api
    build:
      context: .
      dockerfile: Fiap.CloudGames.Fase1.API/Dockerfile
    ports:
      - "4080:4080"
      - "4081:4081"

  cloudgames.database:
    image: postgres:latest
    container_name: cloudgames.database
    environment:
      -  POSTGRES_DB=cloudgames
      -  POSTGRES_USER=postgres
      -  POSTGRES_PASSWORD=postgres
    volumes:
      - ./containers/cloudgames-db:/var/lib/postgresql/data
    ports:
      - 5432:5432