services:
  fiap.cloudgames.fase1.api:
    image: ${DOCKER_REGISTRY-}fiapcloudgamesfase1api
    container_name: fiapcloudgamesfase1api
    build:
      context: .
      dockerfile: Fiap.CloudGames.Fase1.API/Dockerfile
    ports:
      - "4080:4080"
      - "4081:4081"
    environment:
      NEW_RELIC_LICENSE_KEY: 8e036d4bacc7671bbc6088daa6144af9FFFFNRAL # TODO: usar ${NEW_RELIC_LICENSE_KEY} e colocar a chave em um arquivo .env
      NEW_RELIC_APP_NAME: fiapcloudgamesfase1api
      NEW_RELIC_LOG: stdout
      NEW_RELIC_DISTRIBUTED_TRACING_ENABLED: true

  cloudgames.database:
    image: postgres:latest
    container_name: cloudgames.database
    environment:
      -  POSTGRES_DB=cloudgames
      -  POSTGRES_USER=postgres
      -  POSTGRES_PASSWORD=postgres
    volumes:
      - ./containers/cloudgames-db:/var/lib/postgresql/data
    ports:
      - 5432:5432