{
 "title": "ASP.NET Core API Metrics",
 "tags": [
  "aspnetcore",
  "prometheus"
 ],
 "refresh": "5s",
 "panels": [
  {
   "title": "Requisições HTTP por segundo",
   "type": "graph",
   "gridPos": { "x": 0, "y": 0, "w": 12, "h": 8 },
   "targets": [
    {
     "expr": "rate(http_requests_received_total[1m])",
     "legendFormat": "Requisições"
    }
   ]
  },
  {
   "title": "Duração das requisições HTTP (p95)",
   "type": "graph",
   "gridPos": { "x": 12, "y": 0, "w": 12, "h": 8 },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(rate(http_request_duration_seconds_bucket[1m])) by (le))",
     "legendFormat": "p95"
    }
   ]
  },
  {
   "title": "Uso de CPU",
   "type": "graph",
   "gridPos": { "x": 0, "y": 9, "w": 12, "h": 8 },
   "targets": [
    {
     "expr": "rate(process_cpu_seconds_total[1m])",
     "legendFormat": "CPU"
    }
   ]
  },
  {
   "title": "Uso de Memória",
   "type": "graph",
   "gridPos": { "x": 12, "y": 9, "w": 12, "h": 8 },
   "targets": [
    { "expr": "process_working_set_bytes", "legendFormat": "RAM" }
   ]
  }
 ]
}